name: rol.jobs
favicon: null
layout_spectrum: 0.41689927340485156
typography_spectrum: 0.5842739506624639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3050619503483176
  lightness: 0.27915953332558274
  saturation: 0.055432786233723164
  rhythmicContrast: 0.2979940320365131
purpose: []
